### ISSUE TITLE
Issue with Google authentication

### ISSUE THREAD

**Issue by FlowCharter** [FlowCharterOrg/webapp#20]
If a user is already logged in to his google account (say, at chrome), then the authentication is not suggested to him. He just lands on the dashboard with the default authentication (chinese woman picture).
The authentication only works in incognito mode or if the user signed out of all of his accounts in advance.

**Comment by eafzali** [comment]
You sure about it? I guess that's just a caching issue... I suggest you clear your browser cache, so theres no (chinese woman picture) anymore in the code.

**Comment by FlowCharter** [comment]
You're probably right.
Hard refresh didn't solve the problem, but restarting the computer did.
