### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by FlowCharter** [FlowCharterOrg/webapp#27]
I'm having difficulties signing up.
No password I insert is considered "strong" for the validator.
For example, "AmirAmir123" isn't considered strong.
I saw that the regexp being matched is:

^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}

Could it be that the problem is in the regexp?
Please prioritize it so that I can check the feature.

**Comment by eafzali** [comment]
You should also invclude a symbol in your password for example 'Amir@123' would work.

**Comment by FlowCharter** [comment]
OK
