### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by FlowCharter** [FlowCharterOrg/webapp#34]
To insert a comment, the user will right-click on an object. Then a tooltip will show up, with only one option for now: "Add comment".
A comment will associated with the object for which it has been assigned.
The rest of the comments functionality should be the same as in the PDF.

**Comment by eafzali** [comment]
Right click is not a touch friendly solution and is not recommended by
material design guidelines. I suggest adding option menu button beside each
object

**Comment by FlowCharter** [comment]
OK
